[package]
name = "hephasm"
version = "0.1.0"
edition = "2021"

[dependencies]
asmodeus_shared = { path = "../shared" }
parseid = { path = "../parseid" }
lexariel = { path = "../lexariel" }
thiserror = "1.0"

[dev-dependencies]
