[package]
name = "hephasm"
version = "0.1.0"
edition = "2021"

[dependencies]
lexariel = { path = "../lexariel" }
asmodeus_parser = { path = "../asmodeus_parser" }
thiserror = "1.0"

[dev-dependencies]
